### ISSUE TITLE
Raspberry pi zero 2 w no voice command

### ISSUE THREAD

**Issue by Tttyagi123** [nisargjhaveri/WirelessAndroidAutoDongle#208]
"Ok google", activates assistant but does not listen to any command given afterwards.

Many a times while initiating connection even with high speed micro usb and data port connected on raspberry pi, the device keeps trying to find wireless android auto, even if wifi connected manually, the bt keeps on failing to connect, the only way to connect is to unplug the cable from raspberry pi and connect it back, then it connects.

**Comment by Tttyagi123** [comment]
A d once connected, the music on local music app and spotify both stutter from time to time

**Comment by gamelaster** [comment]
Use another Raspberry Pi which have 5 GHz WiFi, which provides higher bandwidth and also is better suited for this. That should resolve your issues.

**Comment by Tttyagi123** [comment]
> Use another Raspberry Pi which have 5 GHz WiFi, which provides higher bandwidth and also is better suited for this. That should resolve your issues.

Will wait till the developer provides a fix for this issue, i know that i can buy a 5g dongle and connect to my pi but the issue is not that frequent as of now so one can live with it till it is resolved

**Comment by gamelaster** [comment]
> Will wait till the developer provides a fix for this issue

Was this somewhere addressed by @nisargjhaveri ?

**Comment by Tttyagi123** [comment]
Only voice command issue remains but that's working intermittently too, thanks.
